### ISSUE TITLE
Investigate Pixate for styling

### ISSUE THREAD

**Issue by trabianmatt** [trabian/titanium-backbone#24]
Now that Pixate is free it might be a better solution than our custom CSS styling. We should at least do a quick spike on it.

https://github.com/Pixate/Titanium-Pixate

**Comment by dwradcliffe** [comment]
I was going to suggest that when I saw the announcement. Looks like it could be really useful.

**Comment by trabianmatt** [comment]
I'm impressed so far. For some reason I was under the impression that it created its own controls rather than styling existing ones. That was just my fault for not digging in.
