### ISSUE TITLE
Running npm install on created app fails

### ISSUE THREAD

**Issue by svallory** [trabian/titanium-backbone#5]
I don't know if its a problem with the build script or with stitch-up but, after running

`titanium-backbone new myapp`
`cd myapp`
`npm install`

I get the following error:

/path/to/myapp/node_modules/titanium-backbone/node_modules/stitch-up/lib/utils/merge.coffee:51
          for (_i = 0, _len = deps.length; _i < _len; _i++) {

**Comment by trabianmatt** [comment]
Interesting -- I'm installing a fresh environment so I can test this out and try to reproduce the issue. It doesn't do it on my box.

**Comment by trabianmatt** [comment]
@svallory, when I run `npm install` on a fresh environment I get the same problem you encountered, which seems to be happening during the `cake build` script as part of the npm install. When I run `cake build` independently after the failed `npm install`, it works fine.

So, I just pushed a new version of titanium-backbone (0.2.4) which generates an app that doesn't call `cake build` automatically as part of `npm install` but, instead, provides instructions to do so.

Hope that helps!

**Comment by svallory** [comment]
cool, thanks!
