### ISSUE TITLE
Consider a shorter name

### ISSUE THREAD

**Issue by trabianmatt** [trabian/titanium-backbone#7]
@svallory and @tonydewan have both been part of discussions regarding the project name. I'm no huge fan of titanium-backbone but haven't really come up with an alternative.

What about keeping the name as 'titanium-backbone' but shortening the command to 'tb'? Any other ideas?

**Comment by tonydewan** [comment]
I like adamantium. It's not much shorter, and there's an [existing (abandoned) project](https://github.com/adamrenklint/Adamantium.js)...but it's just so darn cool.

**Comment by shipstar** [comment]
I liked Tony's suggestion of Adamantium. I like 't-bone' as well

tb doesn't seem to conflict with anything, so I'd be okay with the shortened command. tbone would also be manageable.

**Comment by trabianmatt** [comment]
Will it be a problem that I'm going to be hungry every time I use it?

On Tue, May 29, 2012 at 10:56 AM, Kyle Shipley <
reply@reply.github.com

> wrote:
> 
> I liked Tony's suggestion of Adamantium. I like 't-bone' as well
> 
> tb doesn't seem to conflict with anything, so I'd be okay with the
> shortened command. tbone would also be manageable.
> 
> On Tuesday, May 29, 2012 at 10:51 AM, trabianmatt wrote:
> 
> > @svallory and @tonydewan have both been part of discussions regarding
> > the project name. I'm no huge fan of titanium-backbone but haven't really
> > come up with an alternative.
> > 
> > What about keeping the name as 'titanium-backbone' but shortening the
> > command to 'tb'? Any other ideas?
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/trabian/titanium-backbone/issues/7
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/trabian/titanium-backbone/issues/7#issuecomment-5985833

## 

Matt Dean
President and CEO
Trabian
www.trabian.com

877 603-8011 x701

**Comment by tonydewan** [comment]
How about foam? See: http://www.ipmd.net/articles/000910.html

**Comment by svallory** [comment]
When I commented on the name I was actually thinking about the command. Having the name titanium-backbone was probably what allowed me to find this project.

But I laughed really loud when I read @shipstar suggestion: t-bone!!! ahhahaha

so, I would go for keeping the name and changing the command to t-bone

**Comment by trabianmatt** [comment]
In the 'refactor' branch I've started namespacing the titanium-backbone code using `tb`. I like the idea of using t-bone for the bin name and will use that when I restore the generator functionality within the refactor branch.

Thanks for the suggestions!
