### ISSUE TITLE
discussion goup?

### ISSUE THREAD

**Issue by svallory** [trabian/titanium-backbone#8]
Should we setup a discussion list? Some matters doesn't fit the issues. For example, have you guys looked at kranium? It integrates backbone and a lot of other stuff. It's open source too. Maybe we could learn some lessons from it, or even fork it. I don't know.

**Comment by trabianmatt** [comment]
I just created a Google Group at http://groups.google.com/group/titanium-backbone, though I haven't added anything to it yet.

Regarding Kranium -- I've looked at it briefly and while it didn't quite fit my mental approach to mobile development it certainly looks as though they've done some good work that we could use as inspiration. Was there anything in particular that you really like about it?

**Comment by svallory** [comment]
Great! Already joined the group. About Kranium, I only watched a really vague presentation from his creator on the code strong. I'm going to study it and come back with more thoughts.
